server:  port: 9092  
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
                                         ## corrector de error del timezone
                                         ##"?useTimezone=true&serverTimezone=UTC"
    url: jdbc:mysql://localhost:3306/cliente?useTimezone=true&serverTimezone=UTC
    username: root
    password: '{cipher}mysql'